
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jguptbivgcofgbxnbfjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXB0Yml2Z2NvZmdieG5iZmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTE0MDksImV4cCI6MjA1ODI2NzQwOX0.llRWPou_9dKSUWK3I3TSJ0WOwyvituYDCuFPLE2xZ7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
